apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: "nghz.net/data/certificates"
stringData:
  tls.crt: <ca.pem>
  tls.key: <ca-key.pem>