apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
spec:
  dnsNames:
    - argocd.nghz.net
  secretName: argocd-certificate
  issuerRef:
    name: ca # Use the issuer created previously
    kind: ClusterIssuer
