bases:
- ../../base

configMapGenerator:
- name: argocd-proxy
  envs:
  - proxy.env
  options:
    disableNameSuffixHash: true
- name: argocd-cm
  files:
  - configManagementPlugins
  envs:
  - argocd-cm.env
  options:
    disableNameSuffixHash: true
  behavior: replace
- name: argocd-cmd-params-cm
  envs:
  - argocd-cmd-params-cm.env
  options:
    disableNameSuffixHash: true
  behavior: replace


patchesStrategicMerge:
- deployments.yaml

resources:
- certificates.yaml
- ingressroutes.yaml
# - ingresses.yaml


