apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificates
spec:
  dnsNames:
  - argocd.mayongcong.net
  secretName: argocd.mayongcong.net
  issuerRef:
    name: ca # Use the issuer created previously
    kind: ClusterIssuer
