bases:
- ../../base

configMapGenerator:
- name: argocd-proxy
  envs:
  - proxy.env
  options:
    disableNameSuffixHash: true
- name: argocd-cm
  files:
  - configManagementPlugins
  envs:
  - argocd-cm.env
  options:
    disableNameSuffixHash: true
  behavior: replace
- name: argocd-cmd-params-cm
  envs:
  - argocd-cmd-params-cm.env
  options:
    disableNameSuffixHash: true
  behavior: replace


patchesStrategicMerge:
- argocd-server.yaml
- argocd-repo-server.yaml

resources:
- custom-ca.yaml
- certificates.yaml
- ingressroutes.yaml

