resources:
  # - https://github.com/knative/serving/releases/download/knative-v1.7.1/serving-crds.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.7.1/serving-core.yaml
  - https://github.com/knative/net-kourier/releases/download/knative-v1.7.0/kourier.yaml
  - https://github.com/knative/serving/releases/download/knative-v1.7.1/serving-default-domain.yaml


patchesStrategicMerge:
  - kourier.yaml