apiVersion: v1
kind: Secret
metadata:
  name: metabase
  annotations:
    avp.kubernetes.io/path: "nghz.net/data/postgresql/metabase"
type: Opaque
stringData:
  MB_DB_USER: <username>
  MB_DB_PASS: <password>
  MB_DB_DBNAME: <database>
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: metabase
  annotations:
    avp.kubernetes.io/path: "nghz.net/data/postgresql/metabase"
data:
  MB_DB_TYPE: postgres
  MB_DB_PORT: "5432"
  MB_DB_HOST: postgres-postgresql.common