apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: metabase-redirect-http
  namespace: research-cloud
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`metabase.nghz.net`)
      priority: 1
      middlewares:
        - name: redirect-https
      services:
        - name: metabase
          port: 3000
          passHostHeader: true
          responseForwarding:
            flushInterval: 1ms
          scheme: http        
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: metabase
  namespace: research-cloud
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`metabase.nghz.net`)
      priority: 10
      services:
        - name: metabase
          port: 3000
  tls:
    secretName: research-cloud-certificates