apiVersion: v1
kind: Secret
metadata:
  name: permission-manager
  annotations:
    avp.kubernetes.io/path: "mayongcong.net/data/kubernetes/permission-manager"
type: Opaque
stringData:
  PORT: "4000" # port where server is exposed
  CLUSTER_NAME: "microk8s" # name of the cluster to use in the generated kubeconfig file
  CONTROL_PLANE_ADDRESS: "https://192.168.150.100:16443" # full address of the control plane to use in the generated kubeconfig file
  BASIC_AUTH_PASSWORD: <basic-auth-password> # password used by basic auth (username is `admin`)