apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  annotations:
    avp.kubernetes.io/path: "nghz.net/data/mysql/nacos"
data:
  mysql.db.host: mysql-master
  mysql.db.name: <database>
  mysql.param: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
  mysql.password: <password>
  mysql.port: "3306"
  mysql.user: <username>
