# Default values for nacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  mode: standalone
#  mode: cluster

############################nacos###########################
nacos:
  image:
    repository: nacos/nacos-server
    tag: latest
    pullPolicy: IfNotPresent
  plugin:
    enable: true
    image:
      repository: nacos/nacos-peer-finder-plugin
      tag: 1.1
  replicaCount: 1
  domainName: cluster.local
  preferhostmode: hostname
  serverPort: 8848
  health:
    enabled: false
  storage:
    # type: embedded
    type: mysql
    db:
      host: mysql-master
      name: <path:nghz.net/data/mysql/nacos#database>
      port: 3306
      username: <path:nghz.net/data/mysql/nacos#username>
      password: <path:nghz.net/data/mysql/nacos#password>
      param: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false

persistence:
  enabled: true
  data:
    accessModes:
      - ReadWriteOnce
    storageClassName: nfs-client
    resources:
      requests:
        storage: 5Gi

service:
  type: ClusterIP
  # type: NodePort
  port: 8848
  nodePort: 30000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: nacos.nghz.net
      paths: []

  tls:
    - secretName: common-certificates
      hosts:
        - nacos.nghz.net

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 1Gi
annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
